# Generated by Django 5.1.4 on 2025-09-13 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_orderitem_price_at_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Price adjustment from Product.selling_price (can be positive or negative)', max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='storeapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'name'], name='storeapp_pr_product_fba992_idx'), models.Index(fields=['sku'], name='storeapp_pr_sku_a3b6ca_idx')],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
