# Generated by Django 5.1.4 on 2024-12-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_agent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
