# Generated by Django 5.1.4 on 2024-12-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
