# Generated by Django 5.1.4 on 2024-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_category_parent_order_estimated_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
    ]
