# Generated by Django 5.1.4 on 2024-12-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
