# Generated by Django 5.1.4 on 2024-12-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
