# Generated by Django 5.1.4 on 2024-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_alter_deliveryaddress_full_name_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
