# Generated by Django 5.1.4 on 2024-12-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
